apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "cashu-ledger-web.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "cashu-ledger-web.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "cashu-ledger-web.name" . }}
    spec:
      containers:
        - name: web
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8080
          env:
            - name: SERVER_PORT
              value: "8080"
