server:
  port: 6060

ledger:
  web:
    relays:
      - wss://relay.imani.casa
    timeout: 30s
    cache-ttl: 30s
    api-base: https://staging.imani.casa/api/v1

spring:
  thymeleaf:
    cache: false

  security:
    user:
      name: disabled
      password: disabled
